spring.application.name=gateway

app.version=${APP_VERSION:0.0.1-SNAPSHOT}

spring.config.import=optional:file:local/gateway.properties[.properties]

# overridden in local properties
server.port=8080

logging.config=classpath:log4j2.xml
spring.cloud.gateway.metrics.enabled=false

springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=${SPRINGDOC_API_DOCS_ENABLED:true}
springdoc.swagger-ui.enabled=${SPRINGDOC_SWAGGER_UI_ENABLED:true}

# Security
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:}

# CORS
app.cors.allowedOrigin=${CORS_ALLOWED_ORIGIN:}

# Individual service endpoints
springdoc.swagger-ui.urls[0].name=Merged API
springdoc.swagger-ui.urls[0].url=/gateway/v3/api-docs/merged
springdoc.swagger-ui.urls[1].name=CRM API
springdoc.swagger-ui.urls[1].url=/v3/api-docs/crm
springdoc.swagger-ui.urls[2].name=Employee API
springdoc.swagger-ui.urls[2].url=/v3/api-docs/employee
springdoc.swagger-ui.urls[3].name=Notification API
springdoc.swagger-ui.urls[3].url=/v3/api-docs/notification
springdoc.swagger-ui.urls[4].name=Resource API
springdoc.swagger-ui.urls[4].url=/v3/api-docs/resource
springdoc.swagger-ui.urls[5].name=Sale API
springdoc.swagger-ui.urls[5].url=/v3/api-docs/sale
springdoc.swagger-ui.urls[6].name=Suggestion API
springdoc.swagger-ui.urls[6].url=/v3/api-docs/suggestion
springdoc.swagger-ui.urls[7].name=User API
springdoc.swagger-ui.urls[7].url=/v3/api-docs/user
