spring.application.name=gateway

spring.config.import=optional:file:local/gateway.properties[.properties]

# overridden in local properties
server.port=8080

logging.config=classpath:log4j2.xml

springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=${SPRINGDOC_API_DOCS_ENABLED:true}
springdoc.swagger-ui.enabled=${SPRINGDOC_SWAGGER_UI_ENABLED:true}

# Enable aggregated endpoint
springdoc.swagger-ui.urls[0].name=Merged API
springdoc.swagger-ui.urls[0].url=/gateway/v3/api-docs/merged
springdoc.swagger-ui.urls[1].name=CRM API
springdoc.swagger-ui.urls[1].url=/crm/v3/api-docs
springdoc.swagger-ui.urls[2].name=Employee API
springdoc.swagger-ui.urls[2].url=/employee/v3/api-docs
springdoc.swagger-ui.urls[3].name=Notification API
springdoc.swagger-ui.urls[3].url=/notification/v3/api-docs

