spring.application.name=crm

spring.config.import=optional:file:local/crm.properties[.properties]

# Postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# overridden in local properties
server.port=8080

logging.config=classpath:log4j2.xml

