package org.zerp.common.permission.entity;

import static org.zerp.common.permission.entity.PermissionTargetType.*;

public enum PermissionAction {
    // TENANT level
    ADMIN_TENANT(TENANT),
    UPDATE_TENANT(TENANT),
    READ_TENANT(TENANT),
    CREATE_STOCK_RESOURCE(TENANT),
    CREATE_EMPLOYEE(TENANT),
    CREATE_TICKET(TENANT),
    CREATE_TEAM(TENANT),
    CREATE_STOCK_MOVEMENT(TENANT),
    CREATE_STOCK_COUNT(TENANT),
    CREATE_PRODUCT(TENANT),
    CREATE_PRODUCT_RECIPE(TENANT),
    CREATE_PRODUCT_EXTRA_OPTION(TENANT),
    CREATE_MENU(TENANT),
    CREATE_MENU_CATEGORY(TENANT),
    CREATE_MENU_ITEM(TENANT),

    // USER level
    READ_USER(USER),
    READ_PERMISSION(USER),

    // STOCK_RESOURCE level
    ADMIN_STOCK_RESOURCE(STOCK_RESOURCE),
    UPDATE_STOCK_RESOURCE(STOCK_RESOURCE),
    DELETE_STOCK_RESOURCE(STOCK_RESOURCE),
    READ_STOCK_RESOURCE(STOCK_RESOURCE),

    // EMPLOYEE level
    READ_EMPLOYEE(EMPLOYEE),
    UPDATE_EMPLOYEE(EMPLOYEE),
    DELETE_EMPLOYEE(EMPLOYEE),

    // TEAM level
    READ_TEAM(TEAM),
    UPDATE_TEAM(TEAM),
    DELETE_TEAM(TEAM),
    CREATE_TEAM_MEMBER(TEAM),

    // TEAM_MEMBER level
    READ_TEAM_MEMBER(TEAM_MEMBER),
    UPDATE_TEAM_MEMBER(TEAM_MEMBER),
    DELETE_TEAM_MEMBER(TEAM_MEMBER),

    // TICKET level
    READ_TICKET(TICKET),
    UPDATE_TICKET(TICKET),
    DELETE_TICKET(TICKET),
    CREATE_TICKET_HISTORY(TICKET),
    CREATE_TICKET_COMMENT(TICKET),
    CREATE_TICKET_ASSIGNMENT(TICKET),
    CREATE_TICKET_ATTACHMENT(TICKET),
    CREATE_TICKET_SLA_TRACKING(TICKET),
    CREATE_TICKET_WATCHER(TICKET),

    // TICKET_HISTORY level
    READ_TICKET_HISTORY(TICKET_HISTORY),
    UPDATE_TICKET_HISTORY(TICKET_HISTORY),
    DELETE_TICKET_HISTORY(TICKET_HISTORY),

    // TICKET_COMMENT level
    READ_TICKET_COMMENT(TICKET_COMMENT),
    UPDATE_TICKET_COMMENT(TICKET_COMMENT),
    DELETE_TICKET_COMMENT(TICKET_COMMENT),

    // TICKET_ASSIGNMENT level
    READ_TICKET_ASSIGNMENT(TICKET_ASSIGNMENT),
    UPDATE_TICKET_ASSIGNMENT(TICKET_ASSIGNMENT),
    DELETE_TICKET_ASSIGNMENT(TICKET_ASSIGNMENT),

    // TICKET_ATTACHMENT level
    READ_TICKET_ATTACHMENT(TICKET_ATTACHMENT),
    UPDATE_TICKET_ATTACHMENT(TICKET_ATTACHMENT),
    DELETE_TICKET_ATTACHMENT(TICKET_ATTACHMENT),

    // TICKET_SLA_TRACKING level
    READ_TICKET_SLA_TRACKING(TICKET_SLA_TRACKING),
    UPDATE_TICKET_SLA_TRACKING(TICKET_SLA_TRACKING),
    DELETE_TICKET_SLA_TRACKING(TICKET_SLA_TRACKING),

    // TICKET_WATCHER level
    READ_TICKET_WATCHER(TICKET_WATCHER),
    UPDATE_TICKET_WATCHER(TICKET_WATCHER),
    DELETE_TICKET_WATCHER(TICKET_WATCHER),

    // STOCK_MOVEMENT level
    READ_STOCK_MOVEMENT(STOCK_MOVEMENT),

    // STOCK_COUNT level
    ADMIN_STOCK_COUNT(STOCK_COUNT),
    UPDATE_STOCK_COUNT(STOCK_COUNT),
    DELETE_STOCK_COUNT(STOCK_COUNT),
    READ_STOCK_COUNT(STOCK_COUNT),

    // PRODUCT level
    ADMIN_PRODUCT(PRODUCT),
    UPDATE_PRODUCT(PRODUCT),
    DELETE_PRODUCT(PRODUCT),
    READ_PRODUCT(PRODUCT),

    // PRODUCT_RECIPE level
    ADMIN_PRODUCT_RECIPE(PRODUCT_RECIPE),
    UPDATE_PRODUCT_RECIPE(PRODUCT_RECIPE),
    DELETE_PRODUCT_RECIPE(PRODUCT_RECIPE),
    READ_PRODUCT_RECIPE(PRODUCT_RECIPE),

    // PRODUCT_EXTRA_OPTION level
    ADMIN_PRODUCT_EXTRA_OPTION(PRODUCT_EXTRA_OPTION),
    UPDATE_PRODUCT_EXTRA_OPTION(PRODUCT_EXTRA_OPTION),
    DELETE_PRODUCT_EXTRA_OPTION(PRODUCT_EXTRA_OPTION),
    READ_PRODUCT_EXTRA_OPTION(PRODUCT_EXTRA_OPTION),

    // MENU level
    ADMIN_MENU(MENU),
    UPDATE_MENU(MENU),
    DELETE_MENU(MENU),
    READ_MENU(MENU),

    // MENU_CATEGORY level
    ADMIN_MENU_CATEGORY(MENU_CATEGORY),
    UPDATE_MENU_CATEGORY(MENU_CATEGORY),
    DELETE_MENU_CATEGORY(MENU_CATEGORY),
    READ_MENU_CATEGORY(MENU_CATEGORY),

    // MENU_ITEM level
    ADMIN_MENU_ITEM(MENU_ITEM),
    UPDATE_MENU_ITEM(MENU_ITEM),
    DELETE_MENU_ITEM(MENU_ITEM),
    READ_MENU_ITEM(MENU_ITEM),
    ;

    PermissionAction(PermissionTargetType minTargetType) {
        this.minTargetType = minTargetType;
    }

    public final PermissionTargetType minTargetType;
}
