package org.zerp.common.permission.entity;

import static org.zerp.common.permission.entity.PermissionTargetType.*;

public enum PermissionAction {
    // TENANT_ROOT level
    CREATE_EMPLOYEE_ANY_TENANT(TENANT_ROOT),
    READ_SYSTEM_METRICS(TENANT_ROOT),

    // TENANT level
    ADMIN(TENANT),
    UPDATE_TENANT(TENANT),
    READ_TENANT(TENANT),
    CREATE_EMPLOYEE(TENANT),
    READ_ANNOUNCEMENT(TENANT),
    CREATE_ANNOUNCEMENT(TENANT),
    CREATE_TICKET(TENANT),
    CREATE_TEAM(TENANT),

    // SHOP level
    UPDATE_SHOP(SHOP),
    DELETE_SHOP(SHOP),
    READ_SHOP(SHOP),
    READ_DASHBOARD(SHOP),
    CREATE_STOCK_RESOURCE(SHOP),
    CREATE_PRODUCT(SHOP),
    CREATE_MENU(SHOP),
    CREATE_SHOP_TABLE(SHOP),
    CREATE_STOCK_COUNT(SHOP),
    READ_SALE_HISTORY(SHOP),

    // USER level
    READ_USER(USER),
    READ_PERMISSION(USER),

    // STOCK_RESOURCE level
    UPDATE_STOCK_RESOURCE(STOCK_RESOURCE),
    DELETE_STOCK_RESOURCE(STOCK_RESOURCE),
    READ_STOCK_RESOURCE(STOCK_RESOURCE),
    CREATE_STOCK_MOVEMENT(STOCK_RESOURCE),
    CREATE_STOCK_ENTRY(STOCK_RESOURCE),
    CREATE_STOCK_ADJUSTMENT(STOCK_RESOURCE),
    CREATE_STOCK_WASTE(STOCK_RESOURCE),
    CREATE_STOCK_RETURN(STOCK_RESOURCE),

    // EMPLOYEE level
    READ_EMPLOYEE(EMPLOYEE),
    UPDATE_EMPLOYEE(EMPLOYEE),
    DELETE_EMPLOYEE(EMPLOYEE),

    // TEAM level
    READ_TEAM(TEAM),
    UPDATE_TEAM(TEAM),
    DELETE_TEAM(TEAM),
    CREATE_TEAM_MEMBER(TEAM),

    // TEAM_MEMBER level
    READ_TEAM_MEMBER(TEAM_MEMBER),
    UPDATE_TEAM_MEMBER(TEAM_MEMBER),
    DELETE_TEAM_MEMBER(TEAM_MEMBER),

    // TICKET level
    READ_TICKET(TICKET),
    UPDATE_TICKET(TICKET),
    DELETE_TICKET(TICKET),
    CREATE_TICKET_COMMENT(TICKET),
    CREATE_TICKET_ASSIGNMENT(TICKET),
    CREATE_TICKET_ATTACHMENT(TICKET),
    CREATE_TICKET_WATCHER(TICKET),

    // TICKET_HISTORY level
    READ_TICKET_HISTORY(TICKET_HISTORY),

    // TICKET_COMMENT level
    READ_TICKET_COMMENT(TICKET_COMMENT),
    UPDATE_TICKET_COMMENT(TICKET_COMMENT),
    DELETE_TICKET_COMMENT(TICKET_COMMENT),

    // TICKET_ASSIGNMENT level
    READ_TICKET_ASSIGNMENT(TICKET_ASSIGNMENT),
    UPDATE_TICKET_ASSIGNMENT(TICKET_ASSIGNMENT),
    DELETE_TICKET_ASSIGNMENT(TICKET_ASSIGNMENT),

    // TICKET_ATTACHMENT level
    READ_TICKET_ATTACHMENT(TICKET_ATTACHMENT),
    UPDATE_TICKET_ATTACHMENT(TICKET_ATTACHMENT),
    DELETE_TICKET_ATTACHMENT(TICKET_ATTACHMENT),

    // TICKET_SLA_TRACKING level
    READ_TICKET_SLA_TRACKING(TICKET_SLA_TRACKING),

    // TICKET_WATCHER level
    READ_TICKET_WATCHER(TICKET_WATCHER),
    UPDATE_TICKET_WATCHER(TICKET_WATCHER),
    DELETE_TICKET_WATCHER(TICKET_WATCHER),

    // STOCK_MOVEMENT level
    READ_STOCK_MOVEMENT(STOCK_MOVEMENT),
    UPDATE_STOCK_MOVEMENT(STOCK_MOVEMENT),
    DELETE_STOCK_MOVEMENT(STOCK_MOVEMENT),

    // STOCK_COUNT level
    APPROVE_STOCK_COUNT(STOCK_COUNT),
    UPDATE_STOCK_COUNT(STOCK_COUNT),
    DELETE_STOCK_COUNT(STOCK_COUNT),
    READ_STOCK_COUNT(STOCK_COUNT),

    // PRODUCT level
    UPDATE_PRODUCT(PRODUCT),
    DELETE_PRODUCT(PRODUCT),
    READ_PRODUCT(PRODUCT),
    CREATE_PRODUCT_RECIPE(PRODUCT),
    CREATE_PRODUCT_EXTRA_OPTION(PRODUCT),

    // PRODUCT_RECIPE level
    UPDATE_PRODUCT_RECIPE(PRODUCT_RECIPE),
    DELETE_PRODUCT_RECIPE(PRODUCT_RECIPE),
    READ_PRODUCT_RECIPE(PRODUCT_RECIPE),

    // PRODUCT_EXTRA_OPTION level
    UPDATE_PRODUCT_EXTRA_OPTION(PRODUCT_EXTRA_OPTION),
    DELETE_PRODUCT_EXTRA_OPTION(PRODUCT_EXTRA_OPTION),
    READ_PRODUCT_EXTRA_OPTION(PRODUCT_EXTRA_OPTION),

    // MENU level
    UPDATE_MENU(MENU),
    DELETE_MENU(MENU),
    READ_MENU(MENU),
    CREATE_MENU_CATEGORY(MENU),

    // MENU_CATEGORY level
    UPDATE_MENU_CATEGORY(MENU_CATEGORY),
    DELETE_MENU_CATEGORY(MENU_CATEGORY),
    READ_MENU_CATEGORY(MENU_CATEGORY),
    CREATE_MENU_ITEM(MENU_CATEGORY),

    // MENU_ITEM level
    UPDATE_MENU_ITEM(MENU_ITEM),
    DELETE_MENU_ITEM(MENU_ITEM),
    READ_MENU_ITEM(MENU_ITEM),

    // SHOP_TABLE level
    UPDATE_SHOP_TABLE(SHOP_TABLE),
    DELETE_SHOP_TABLE(SHOP_TABLE),
    READ_SHOP_TABLE(SHOP_TABLE),
    CREATE_TABLE_ORDER(SHOP_TABLE),

    // TABLE_ORDER level
    UPDATE_TABLE_ORDER(TABLE_ORDER),
    DELETE_TABLE_ORDER(TABLE_ORDER),
    READ_TABLE_ORDER(TABLE_ORDER),
    ;

    PermissionAction(PermissionTargetType minTargetType) {
        this.minTargetType = minTargetType;
    }

    public final PermissionTargetType minTargetType;
}
