export const queryKeys = {
  tenant: {
    storeSummary:   ['tenant', 'store-summary'] as const,
    salesDashboard: ['tenant', 'sales-dashboard'] as const,
    shopDashboard:  ['tenant', 'shop-dashboard'] as const,
    employees:      ['tenant', 'employees'] as const,
    tickets:        ['tenant', 'tickets'] as const,
    permissions:    ['tenant', 'permissions'] as const,
    permissionGroups: ['tenant', 'permission-groups'] as const,
    notifications:  ['tenant', 'notifications'] as const,
    stockResources:      ['tenant', 'stock-resources'] as const,
    stockOverview:       ['tenant', 'stock-overview'] as const,
    stockMovements:      ['tenant', 'stock-movements'] as const,
    stockMovementTimeline: ['tenant', 'stock-movement-timeline'] as const,
    stockMovementDrillDown: ['tenant', 'stock-movement-drill-down'] as const,
    stockOperations:     ['tenant', 'stock-operations'] as const,
    stockCounts:         ['tenant', 'stock-counts'] as const,
    products:            ['tenant', 'products'] as const,
    productRecipes:      ['tenant', 'product-recipes'] as const,
    productExtraOptions: ['tenant', 'product-extra-options'] as const,
    menus:               ['tenant', 'menus'] as const,
    menuCategories:      ['tenant', 'menu-categories'] as const,
    menuItems:           ['tenant', 'menu-items'] as const,
    shopTables:          ['tenant', 'shop-tables'] as const,
    tableOrders:         ['tenant', 'table-orders'] as const,
    shops:               ['tenant', 'shops'] as const,
  },
  client: {
    stores: ['client', 'stores'] as const,
    orders: ['client', 'orders'] as const,
  },
  admin: {
    tenants: ['admin', 'tenants'] as const,
    health: ['admin', 'health'] as const,
  },
}
