spring.application.name=user

spring.config.import=optional:file:local/user.properties[.properties]

# Postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

server.port=8087

logging.config=classpath:log4j2.xml

keycloak.admin.server-url=${KEYCLOAK_ADMIN_SERVER_URL}
keycloak.admin.realm=${KEYCLOAK_ADMIN_REALM:zerp}
keycloak.admin.client-id=${KEYCLOAK_ADMIN_CLIENT_ID:zerp-admin-cli}
keycloak.admin.client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET}
