spring.application.name=user

server.port=8087

# Postgres config
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://eureka:8761/eureka/}

keycloak.admin.server-url=${KEYCLOAK_ADMIN_SERVER_URL:}
keycloak.admin.realm=${KEYCLOAK_ADMIN_REALM:zerp}
keycloak.admin.client-id=${KEYCLOAK_ADMIN_CLIENT_ID:zerp-admin-cli}
keycloak.admin.client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET:}

user.thumbor.host=${THUMBOR_HOST:http://thumbor:8888}
s3.repository.endpoint=${MINIO_ENDPOINT:http://minio:9000}

app.prometheus.base-url=${PROMETHEUS_BASE_URL:http://prometheus:9090}
app.prometheus.max-range-seconds=${PROMETHEUS_MAX_RANGE_SECONDS:604800}

spring.jpa.hibernate.ddl-auto={SPRING_JPA_HIBERNATE_DDL_AUTO:none}
