spring.application.name=employee

spring.config.import:optional:file:.env[.properties]

# Postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/${POSTGRES_DB:zerp}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:1234}

server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

logging.config=classpath:log4j2.xml
