import { ROUTES } from '@/core/constants/routes'

import type { ShopResponseDto } from '../types/shop'
import type { ShopDashboardData } from '../types/shop-dashboard'

export const shopDashboardMockShops: ShopResponseDto[] = [
  { id: 'shop-kadikoy', name: 'Kadıköy Şubesi', tenantId: 'tenant-mock' },
  { id: 'shop-besiktas', name: 'Beşiktaş Şubesi', tenantId: 'tenant-mock' },
  { id: 'shop-beyoglu', name: 'Beyoğlu Şubesi', tenantId: 'tenant-mock' },
  { id: 'shop-uskudar', name: 'Üsküdar Şubesi', tenantId: 'tenant-mock' },
]

const quickActions = [
  {
    id: 'view-stock' as const,
    label: 'Stoku Görüntüle',
    description: 'Bu şubeye ait kritik stok hareketlerini incele.',
    href: ROUTES.stock,
  },
  {
    id: 'open-cashier' as const,
    label: 'Kasaya Git',
    description: 'Anlık sipariş ve ödeme operasyonunu aç.',
    href: ROUTES.sale,
  },
]

export const shopDashboardMockById: Record<string, ShopDashboardData> = {
  'shop-kadikoy': {
    shopId: 'shop-kadikoy',
    shopName: 'Kadıköy Şubesi',
    subtitle: 'Mağaza özel operasyon görünümü ve satış özeti.',
    reportDateLabel: '17 Mayıs 2026',
    rangeLabel: '7 Gün',
    lastUpdatedAt: '2026-05-17T21:15:00+03:00',
    metrics: [
      {
        id: 'dailyRevenue',
        label: 'Bugünkü Ciro',
        value: 28430,
        unit: 'currency',
        delta: { value: 12, unit: 'percent', direction: 'up', comparisonLabel: 'Düne göre' },
        secondaryLabel: 'Dün: ₺25.390',
      },
      {
        id: 'averageCheck',
        label: 'Ortalama Adisyon',
        value: 412,
        unit: 'currency',
        delta: { value: 8, unit: 'percent', direction: 'up', comparisonLabel: 'Düne göre' },
        secondaryLabel: 'Dün: ₺382',
      },
      {
        id: 'activeTables',
        label: 'Aktif Masa',
        value: '14 / 20',
        unit: 'text',
        progress: { value: 70, label: '%70 doluluk oranı', color: '#f59e0b' },
      },
      {
        id: 'cancelRate',
        label: 'İptal Oranı',
        value: 2.1,
        unit: 'percent',
        delta: { value: 0.6, unit: 'percent', direction: 'down', comparisonLabel: 'Düne göre' },
        secondaryLabel: 'Dün: %2.7',
      },
    ],
    trend: [
      { label: '11 May', revenue: 22400, averageCheck: 210 },
      { label: '12 May', revenue: 23600, averageCheck: 260 },
      { label: '13 May', revenue: 22800, averageCheck: 305 },
      { label: '14 May', revenue: 22950, averageCheck: 290 },
      { label: '15 May', revenue: 31200, averageCheck: 360 },
      { label: '16 May', revenue: 30300, averageCheck: 320 },
      { label: '17 May', revenue: 27450, averageCheck: 255 },
    ],
    salesChannels: [
      { label: 'Masa Servisi', value: 164, percentage: 46.1, color: '#20b486' },
      { label: 'Gel-Al', value: 88, percentage: 24.7, color: '#3b82f6' },
      { label: 'Paket', value: 61, percentage: 17.1, color: '#f59e0b' },
      { label: 'Online Sipariş', value: 43, percentage: 12.1, color: '#fb7185' },
    ],
    categorySales: [
      { id: 'cat-coffee', label: 'Kahve', sales: 10240, percentage: 36, color: '#20b486' },
      { id: 'cat-dessert', label: 'Tatlı', sales: 7680, percentage: 27, color: '#3b82f6' },
      { id: 'cat-cold', label: 'Soğuk İçecek', sales: 5420, percentage: 19, color: '#8b5cf6' },
      { id: 'cat-food', label: 'Yiyecek', sales: 3890, percentage: 14, color: '#f59e0b' },
      { id: 'cat-other', label: 'Diğer', sales: 1200, percentage: 4, color: '#94a3b8' },
    ],
    topProducts: [
      { id: 'prod-1', name: 'Espresso', soldCount: 82, revenue: 4100 },
      { id: 'prod-2', name: 'Latte', soldCount: 68, revenue: 3400 },
      { id: 'prod-3', name: 'Türk Kahvesi', soldCount: 55, revenue: 2200 },
      { id: 'prod-4', name: 'Cheesecake', soldCount: 37, revenue: 1850 },
      { id: 'prod-5', name: 'Mocha', soldCount: 29, revenue: 1450 },
    ],
    performance: [
      { id: 'perf-revenue', label: 'Toplam Ciro', value: 612450, unit: 'currency', deltaText: '+15%' },
      { id: 'perf-check', label: 'Toplam Adisyon', value: 398, unit: 'currency', deltaText: '+6%' },
      { id: 'perf-service', label: 'Toplam Masa Servis Sayısı', value: 1284, unit: 'count', deltaText: '+11%' },
      { id: 'perf-satisfaction', label: 'Müşteri Memnuniyeti', value: '4.2 / 5', unit: 'text' },
    ],
    lowStock: [
      { id: 'stock-1', name: 'Espresso Çekirdeği', remainingLabel: '1.4 kg / eşik 3 kg', progress: 28, statusLabel: 'Kritik', tone: 'critical' },
      { id: 'stock-2', name: 'Tam Yağlı Süt', remainingLabel: '6 lt / eşik 12 lt', progress: 42, statusLabel: 'Düşük', tone: 'warning' },
      { id: 'stock-3', name: 'Cheesecake Dilimi', remainingLabel: '4 adet / eşik 10 adet', progress: 40, statusLabel: 'Düşük', tone: 'warning' },
    ],
    quickActions,
  },
  'shop-besiktas': {
    shopId: 'shop-besiktas',
    shopName: 'Beşiktaş Şubesi',
    subtitle: 'Yoğun yaya trafiğine sahip mağaza için günlük satış görünümü.',
    reportDateLabel: '17 Mayıs 2026',
    rangeLabel: '7 Gün',
    lastUpdatedAt: '2026-05-17T21:10:00+03:00',
    metrics: [
      { id: 'dailyRevenue', label: 'Bugünkü Ciro', value: 26380, unit: 'currency', delta: { value: 9, unit: 'percent', direction: 'up', comparisonLabel: 'Düne göre' }, secondaryLabel: 'Dün: ₺24.200' },
      { id: 'averageCheck', label: 'Ortalama Adisyon', value: 398, unit: 'currency', delta: { value: 4, unit: 'percent', direction: 'up', comparisonLabel: 'Düne göre' }, secondaryLabel: 'Dün: ₺384' },
      { id: 'activeTables', label: 'Aktif Masa', value: '11 / 18', unit: 'text', progress: { value: 61, label: '%61 doluluk oranı', color: '#f59e0b' } },
      { id: 'cancelRate', label: 'İptal Oranı', value: 1.8, unit: 'percent', delta: { value: 0.4, unit: 'percent', direction: 'down', comparisonLabel: 'Düne göre' }, secondaryLabel: 'Dün: %2.2' },
    ],
    trend: [
      { label: '11 May', revenue: 19800, averageCheck: 205 },
      { label: '12 May', revenue: 20550, averageCheck: 235 },
      { label: '13 May', revenue: 21200, averageCheck: 248 },
      { label: '14 May', revenue: 21880, averageCheck: 250 },
      { label: '15 May', revenue: 26600, averageCheck: 312 },
      { label: '16 May', revenue: 27400, averageCheck: 330 },
      { label: '17 May', revenue: 26380, averageCheck: 295 },
    ],
    salesChannels: [
      { label: 'Masa Servisi', value: 142, percentage: 43.2, color: '#20b486' },
      { label: 'Gel-Al', value: 95, percentage: 28.9, color: '#3b82f6' },
      { label: 'Paket', value: 58, percentage: 17.6, color: '#f59e0b' },
      { label: 'Online Sipariş', value: 34, percentage: 10.3, color: '#fb7185' },
    ],
    categorySales: [
      { id: 'cat-coffee-b', label: 'Kahve', sales: 9440, percentage: 34, color: '#20b486' },
      { id: 'cat-dessert-b', label: 'Tatlı', sales: 7060, percentage: 26, color: '#3b82f6' },
      { id: 'cat-cold-b', label: 'Soğuk İçecek', sales: 5800, percentage: 21, color: '#8b5cf6' },
      { id: 'cat-food-b', label: 'Yiyecek', sales: 3560, percentage: 13, color: '#f59e0b' },
      { id: 'cat-other-b', label: 'Diğer', sales: 1520, percentage: 6, color: '#94a3b8' },
    ],
    topProducts: [
      { id: 'prod-b-1', name: 'Cold Brew', soldCount: 74, revenue: 4440 },
      { id: 'prod-b-2', name: 'Flat White', soldCount: 61, revenue: 3355 },
      { id: 'prod-b-3', name: 'Cookie', soldCount: 53, revenue: 1855 },
      { id: 'prod-b-4', name: 'San Sebastian', soldCount: 34, revenue: 2550 },
      { id: 'prod-b-5', name: 'Americano', soldCount: 32, revenue: 1600 },
    ],
    performance: [
      { id: 'perf-revenue-b', label: 'Toplam Ciro', value: 558300, unit: 'currency', deltaText: '+11%' },
      { id: 'perf-check-b', label: 'Toplam Adisyon', value: 382, unit: 'currency', deltaText: '+4%' },
      { id: 'perf-service-b', label: 'Toplam Masa Servis Sayısı', value: 1172, unit: 'count', deltaText: '+8%' },
      { id: 'perf-satisfaction-b', label: 'Müşteri Memnuniyeti', value: '4.4 / 5', unit: 'text' },
    ],
    lowStock: [
      { id: 'stock-b-1', name: 'Matcha Tozu', remainingLabel: '0.8 kg / eşik 2 kg', progress: 24, statusLabel: 'Kritik', tone: 'critical' },
      { id: 'stock-b-2', name: 'Yulaf Sütü', remainingLabel: '5 lt / eşik 10 lt', progress: 50, statusLabel: 'Düşük', tone: 'warning' },
      { id: 'stock-b-3', name: 'Brownie', remainingLabel: '6 adet / eşik 12 adet', progress: 50, statusLabel: 'Düşük', tone: 'warning' },
    ],
    quickActions,
  },
  'shop-beyoglu': {
    shopId: 'shop-beyoglu',
    shopName: 'Beyoğlu Şubesi',
    subtitle: 'Turistik bölge satış temposunu izlemek için mağaza görünümü.',
    reportDateLabel: '17 Mayıs 2026',
    rangeLabel: '7 Gün',
    lastUpdatedAt: '2026-05-17T21:05:00+03:00',
    metrics: [
      { id: 'dailyRevenue', label: 'Bugünkü Ciro', value: 22140, unit: 'currency', delta: { value: 6, unit: 'percent', direction: 'up', comparisonLabel: 'Düne göre' }, secondaryLabel: 'Dün: ₺20.870' },
      { id: 'averageCheck', label: 'Ortalama Adisyon', value: 376, unit: 'currency', delta: { value: 3, unit: 'percent', direction: 'up', comparisonLabel: 'Düne göre' }, secondaryLabel: 'Dün: ₺364' },
      { id: 'activeTables', label: 'Aktif Masa', value: '9 / 16', unit: 'text', progress: { value: 56, label: '%56 doluluk oranı', color: '#f59e0b' } },
      { id: 'cancelRate', label: 'İptal Oranı', value: 2.4, unit: 'percent', delta: { value: 0.2, unit: 'percent', direction: 'down', comparisonLabel: 'Düne göre' }, secondaryLabel: 'Dün: %2.6' },
    ],
    trend: [
      { label: '11 May', revenue: 17400, averageCheck: 188 },
      { label: '12 May', revenue: 18200, averageCheck: 210 },
      { label: '13 May', revenue: 19150, averageCheck: 225 },
      { label: '14 May', revenue: 20400, averageCheck: 240 },
      { label: '15 May', revenue: 23600, averageCheck: 288 },
      { label: '16 May', revenue: 22950, averageCheck: 272 },
      { label: '17 May', revenue: 22140, averageCheck: 264 },
    ],
    salesChannels: [
      { label: 'Masa Servisi', value: 128, percentage: 41.4, color: '#20b486' },
      { label: 'Gel-Al', value: 82, percentage: 26.5, color: '#3b82f6' },
      { label: 'Paket', value: 55, percentage: 17.8, color: '#f59e0b' },
      { label: 'Online Sipariş', value: 44, percentage: 14.3, color: '#fb7185' },
    ],
    categorySales: [
      { id: 'cat-coffee-c', label: 'Kahve', sales: 8360, percentage: 33, color: '#20b486' },
      { id: 'cat-dessert-c', label: 'Tatlı', sales: 6740, percentage: 26, color: '#3b82f6' },
      { id: 'cat-cold-c', label: 'Soğuk İçecek', sales: 4940, percentage: 19, color: '#8b5cf6' },
      { id: 'cat-food-c', label: 'Yiyecek', sales: 3520, percentage: 14, color: '#f59e0b' },
      { id: 'cat-other-c', label: 'Diğer', sales: 1640, percentage: 8, color: '#94a3b8' },
    ],
    topProducts: [
      { id: 'prod-c-1', name: 'Türk Kahvesi', soldCount: 79, revenue: 3160 },
      { id: 'prod-c-2', name: 'Latte', soldCount: 58, revenue: 2900 },
      { id: 'prod-c-3', name: 'Limonata', soldCount: 51, revenue: 2040 },
      { id: 'prod-c-4', name: 'Cheesecake', soldCount: 33, revenue: 1650 },
      { id: 'prod-c-5', name: 'Bagel', soldCount: 27, revenue: 1620 },
    ],
    performance: [
      { id: 'perf-revenue-c', label: 'Toplam Ciro', value: 486210, unit: 'currency', deltaText: '+8%' },
      { id: 'perf-check-c', label: 'Toplam Adisyon', value: 364, unit: 'currency', deltaText: '+3%' },
      { id: 'perf-service-c', label: 'Toplam Masa Servis Sayısı', value: 1038, unit: 'count', deltaText: '+7%' },
      { id: 'perf-satisfaction-c', label: 'Müşteri Memnuniyeti', value: '4.1 / 5', unit: 'text' },
    ],
    lowStock: [
      { id: 'stock-c-1', name: 'Espresso Çekirdeği', remainingLabel: '1.1 kg / eşik 3 kg', progress: 22, statusLabel: 'Kritik', tone: 'critical' },
      { id: 'stock-c-2', name: 'Limon Şurubu', remainingLabel: '3 lt / eşik 7 lt', progress: 43, statusLabel: 'Düşük', tone: 'warning' },
      { id: 'stock-c-3', name: 'San Sebastian', remainingLabel: '5 adet / eşik 11 adet', progress: 45, statusLabel: 'Düşük', tone: 'warning' },
    ],
    quickActions,
  },
  'shop-uskudar': {
    shopId: 'shop-uskudar',
    shopName: 'Üsküdar Şubesi',
    subtitle: 'Mahalle trafiği ve servis yoğunluğu için günlük operasyon özeti.',
    reportDateLabel: '17 Mayıs 2026',
    rangeLabel: '7 Gün',
    lastUpdatedAt: '2026-05-17T20:58:00+03:00',
    metrics: [
      { id: 'dailyRevenue', label: 'Bugünkü Ciro', value: 19620, unit: 'currency', delta: { value: 7, unit: 'percent', direction: 'up', comparisonLabel: 'Düne göre' }, secondaryLabel: 'Dün: ₺18.340' },
      { id: 'averageCheck', label: 'Ortalama Adisyon', value: 352, unit: 'currency', delta: { value: 5, unit: 'percent', direction: 'up', comparisonLabel: 'Düne göre' }, secondaryLabel: 'Dün: ₺336' },
      { id: 'activeTables', label: 'Aktif Masa', value: '10 / 15', unit: 'text', progress: { value: 67, label: '%67 doluluk oranı', color: '#f59e0b' } },
      { id: 'cancelRate', label: 'İptal Oranı', value: 1.6, unit: 'percent', delta: { value: 0.3, unit: 'percent', direction: 'down', comparisonLabel: 'Düne göre' }, secondaryLabel: 'Dün: %1.9' },
    ],
    trend: [
      { label: '11 May', revenue: 15100, averageCheck: 172 },
      { label: '12 May', revenue: 16240, averageCheck: 188 },
      { label: '13 May', revenue: 17120, averageCheck: 214 },
      { label: '14 May', revenue: 16850, averageCheck: 208 },
      { label: '15 May', revenue: 20520, averageCheck: 262 },
      { label: '16 May', revenue: 21340, averageCheck: 284 },
      { label: '17 May', revenue: 19620, averageCheck: 248 },
    ],
    salesChannels: [
      { label: 'Masa Servisi', value: 121, percentage: 44.6, color: '#20b486' },
      { label: 'Gel-Al', value: 67, percentage: 24.7, color: '#3b82f6' },
      { label: 'Paket', value: 49, percentage: 18, color: '#f59e0b' },
      { label: 'Online Sipariş', value: 34, percentage: 12.7, color: '#fb7185' },
    ],
    categorySales: [
      { id: 'cat-coffee-d', label: 'Kahve', sales: 7140, percentage: 32, color: '#20b486' },
      { id: 'cat-dessert-d', label: 'Tatlı', sales: 5960, percentage: 27, color: '#3b82f6' },
      { id: 'cat-cold-d', label: 'Soğuk İçecek', sales: 4280, percentage: 19, color: '#8b5cf6' },
      { id: 'cat-food-d', label: 'Yiyecek', sales: 3320, percentage: 15, color: '#f59e0b' },
      { id: 'cat-other-d', label: 'Diğer', sales: 1660, percentage: 7, color: '#94a3b8' },
    ],
    topProducts: [
      { id: 'prod-d-1', name: 'Filtre Kahve', soldCount: 66, revenue: 2640 },
      { id: 'prod-d-2', name: 'Mocha', soldCount: 48, revenue: 2400 },
      { id: 'prod-d-3', name: 'Muffin', soldCount: 44, revenue: 1760 },
      { id: 'prod-d-4', name: 'Iced Latte', soldCount: 35, revenue: 2100 },
      { id: 'prod-d-5', name: 'Cookie', soldCount: 29, revenue: 1160 },
    ],
    performance: [
      { id: 'perf-revenue-d', label: 'Toplam Ciro', value: 428940, unit: 'currency', deltaText: '+9%' },
      { id: 'perf-check-d', label: 'Toplam Adisyon', value: 341, unit: 'currency', deltaText: '+5%' },
      { id: 'perf-service-d', label: 'Toplam Masa Servis Sayısı', value: 972, unit: 'count', deltaText: '+6%' },
      { id: 'perf-satisfaction-d', label: 'Müşteri Memnuniyeti', value: '4.3 / 5', unit: 'text' },
    ],
    lowStock: [
      { id: 'stock-d-1', name: 'Filtre Kahve Çekirdeği', remainingLabel: '1.6 kg / eşik 3 kg', progress: 34, statusLabel: 'Düşük', tone: 'warning' },
      { id: 'stock-d-2', name: 'Badem Sütü', remainingLabel: '4 lt / eşik 9 lt', progress: 44, statusLabel: 'Düşük', tone: 'warning' },
      { id: 'stock-d-3', name: 'Muffin', remainingLabel: '3 adet / eşik 8 adet', progress: 38, statusLabel: 'Kritik', tone: 'critical' },
    ],
    quickActions,
  },
}
