services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped

    ports:
      - "127.0.0.1:9898:8080"

    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

    privileged: true

    devices:
      - /dev/kmsg

    mem_limit: 128m

    networks:
      - zerp-net

networks:
  zerp-net:
    external: true