services:
  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ../zerp-backend/logs:/usr/share/logstash/logs:ro
      - logstash-data:/usr/share/logstash/data
#    environment:
      #- LS_JAVA_OPTS=-Xmx256m -Xms256m
    depends_on:
      opensearch:
        condition: service_healthy
    networks:
      - logging-network


  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
#      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Wk3998SUJny!
      - plugins.security.ssl.http.enabled=false
      # - plugins.security.ssl.http.pemcert_filepath=certs/opensearch.pem
      # - plugins.security.ssl.http.pemkey_filepath=certs/opensearch-key.pem
      # - plugins.security.ssl.http.pemtrustedcas_filepath=certs/root-ca.pem
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200" # OpenSearch API
      - "9600:9600" # Performans izleme
    healthcheck:
      test: ["CMD-SHELL", "curl -s -o /dev/null -w '%{http_code}' http://localhost:9200 | grep -Eq '^(200|401)$'"]
      start_period: 60s
      interval: 10s
      timeout: 5s
      retries: 12
    networks:
      - logging-network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      # - SERVER_HOST=0.0.0.0
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=Wk3998SUJny!
    volumes:
      - opensearch-dashboard-data:/usr/share/opensearch-dashboards/data
    ports:
      - "5601:5601"
    networks:
      - logging-network
    depends_on:
      opensearch:
        condition: service_healthy


volumes:
  opensearch-data:
  opensearch-dashboard-data:
  logstash-data:

networks:
  logging-network:
    driver: bridge
