input {
  file {
    path => "/usr/share/logstash/logs/*/*.log"
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/sincedb-zerp-logs"
    codec => multiline {
      pattern => "^%{TIMESTAMP_ISO8601} "
      negate => true
      what => "previous"
      auto_flush_interval => 2
    }
  }
}

filter {
  grok {
    match => {
      "message" => "(?m)%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} \[%{DATA:thread}\] \[correlationId=%{DATA:correlation_id}\] \[clientIp=%{DATA:client_ip}\] %{JAVACLASS:logger} - %{GREEDYDATA:msg}"
    }
  }

  date {
    match => ["timestamp", "yyyy-MM-dd HH:mm:ss.SSSXXX", "yyyy-MM-dd HH:mm:ss.SSS"]
    target => "@timestamp"
    timezone => "Europe/Istanbul"
  }

  grok {
    match => {
      "path" => "/usr/share/logstash/logs/%{DATA:service}/%{GREEDYDATA:log_file}"
    }
  }

  mutate {
    add_field => { "application" => "zerp" }
    remove_field => ["timestamp"]
  }
}

output {
  opensearch {
    hosts => ["http://opensearch:9200"]
    user => "admin"
    password => "Wk3998SUJny!"
    ssl => false
    index => "zerp-%{service}-logs-%{+YYYY.MM.dd}"
  }
}
