spring.application.name=employee

server.port=8080

# Postgres config
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://eureka:8761/eureka/}

user.thumbor.host=${THUMBOR_HOST:http://thumbor:8888}
s3.repository.endpoint=${MINIO_ENDPOINT:http://minio:9000}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
