app.cors.allowedOrigin=${CORS_ALLOWED_ORIGIN:}
spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=1
spring.data.redis.timeout=2000ms

redis.privacy.setting.channel=privacy.setting.changed

server.port=8400

presence.timeout=90
app.websocket.rateLimit.timeWindowMs=60000
app.websocket.rateLimit.maxMessagesPerMinute=60

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://eureka:8761/eureka/}
