spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/zerp
    username: postgres
    password: 1234
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
logging:
  config: classpath:log4j2-docker.xml
