spring.application.name=notification

app.version=${APP_VERSION:0.0.1-SNAPSHOT}

spring.config.import=optional:file:local/notification.properties[.properties]

server.port=8083

spring.datasource.driver-class-name=org.postgresql.Driver

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.config=classpath:log4j2.xml

kafka.url=localhost:29092
kafka.topic.email=email-notifications
openapi.server-urls=${OPENAPI_SERVER_URLS:http://localhost:8080/}
